<a href="https://colab.research.google.com/github/MochamadPhilliaWibowo/Machine-Learning-Class/blob/main/Tugas%20Week%2013/BAB%202/Handling_multiple_sequences_(PyTorch).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nama : Mochamad Phillia Wibowo

NIM : 1103204191

Kelas : Machine Learning (TK-44-G04)

Tugas 13 NLP HUGGING FACE (BAB 2)

# Handling multiple sequences (PyTorch)

Install the Transformers, Datasets, and Evaluate libraries to run this notebook.

In [1]:
!pip install datasets evaluate transformers[sentencepiece]

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.1/542.1 kB 6.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 5.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 6.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 4.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 10.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 9.6 MB/s eta 0:00:00
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.31.0, but you have requests 2.32.3 which is incompatible.


Code di atas adalah perintah untuk menginstal beberapa pustaka Python menggunakan pip, manajer paket standar untuk Python. Perintah ini melakukan instalasi tiga pustaka:

datasets: Ini adalah pustaka yang menyediakan akses mudah ke berbagai kumpulan data untuk tugas-tugas pembelajaran mesin dan pemrosesan bahasa alami.

evaluate: Ini mungkin adalah pustaka khusus yang digunakan untuk mengevaluasi model-model pembelajaran mesin atau pemrosesan bahasa alami, tetapi tanpa informasi lebih lanjut, sulit untuk mengkonfirmasi.

transformers[sentencepiece]: Ini adalah pustaka yang populer digunakan untuk pemrosesan bahasa alami, terutama dalam bidang pemodelan bahasa dan transfer pembelajaran. Opsi [sentencepiece] menunjukkan bahwa instalasi juga akan mencakup dukungan untuk SentencePiece, sebuah pustaka tokenisasi teks multibahasa.

Dengan menjalankan perintah ini, pustaka-pustaka ini akan diinstal dan siap digunakan dalam pengembangan aplikasi Python Anda.

In [5]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = torch.tensor(ids).unsqueeze(0)  # Menambahkan dimensi batch

# Sekarang Anda bisa menggunakan model
outputs = model(input_ids)

# Melakukan softmax terhadap logits untuk mendapatkan probabilitas kelas
probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)

# Membaca kelas yang diprediksi dari probabilitas
id2label = model.config.id2label
predicted_class_id = torch.argmax(probabilities, dim=-1).item()
predicted_class_label = id2label[predicted_class_id]

print("Predicted class:", predicted_class_label)
print("Probabilities:", probabilities)

Predicted class: POSITIVE
Probabilities: tensor([[0.0037, 0.9963]], grad_fn=<SoftmaxBackward0>)


import torch: Ini adalah baris yang mengimpor pustaka PyTorch, yang digunakan untuk operasi-operasi tensor dan pemrosesan di dalam model neural network.

from transformers import AutoTokenizer, AutoModelForSequenceClassification: Baris ini mengimpor dua kelas dari pustaka Transformers:

AutoTokenizer: Digunakan untuk menginisialisasi dan memuat tokenizer yang sesuai dengan model yang akan digunakan.
AutoModelForSequenceClassification: Digunakan untuk menginisialisasi dan memuat model yang telah di-pretrained untuk tugas klasifikasi urutan teks.
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english": Ini adalah string yang berisi nama atau path model yang akan digunakan. Dalam hal ini, model yang dipilih adalah "distilbert-base-uncased-finetuned-sst-2-english", yang merupakan model DistilBERT yang telah di-fineturn pada tugas analisis sentimen (SST-2) dalam bahasa Inggris.

tokenizer = AutoTokenizer.from_pretrained(checkpoint): Baris ini memuat tokenizer yang sesuai dengan model yang telah ditentukan dalam variabel checkpoint. Tokenizer ini akan digunakan untuk memproses teks sebelum diberikan kepada model.

model = AutoModelForSequenceClassification.from_pretrained(checkpoint): Baris ini memuat model yang sesuai dengan model yang telah ditentukan dalam variabel checkpoint. Model ini akan digunakan untuk melakukan klasifikasi urutan teks.

sequence = "I've been waiting for a HuggingFace course my whole life.": Ini adalah teks yang akan diberikan kepada model untuk melakukan prediksi kelas.

tokens = tokenizer.tokenize(sequence): Baris ini menggunakan tokenizer yang telah diinisialisasi sebelumnya untuk memecah teks menjadi token-token. Tokenisasi memecah teks menjadi bagian-bagian yang lebih kecil yang disebut token, yang nantinya akan dimasukkan ke dalam model untuk analisis.

ids = tokenizer.convert_tokens_to_ids(tokens): Baris ini mengonversi token-token menjadi ID-token yang sesuai dengan kamus token yang digunakan oleh model. Ini diperlukan karena model menerima input dalam bentuk ID-token, bukan teks mentah.

input_ids = torch.tensor(ids).unsqueeze(0): Baris ini mengubah ID-token menjadi tensor PyTorch dan menambahkan dimensi batch ke tensor tersebut. Model memerlukan input dalam bentuk batch, bahkan jika ukurannya hanya 1.

outputs = model(input_ids): Baris ini menggunakan model untuk melakukan prediksi kelas berdasarkan input yang diberikan. Model akan menghasilkan output berupa tensor yang berisi nilai-nilai logits untuk setiap kelas.

probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1): Baris ini menggunakan fungsi softmax untuk mengonversi logits yang dihasilkan oleh model menjadi probabilitas untuk setiap kelas. Ini memungkinkan kita untuk menafsirkan prediksi model sebagai probabilitas distribusi kelas.

id2label = model.config.id2label: Baris ini mengakses atribut id2label dari konfigurasi model untuk mendapatkan pemetaan dari ID kelas ke label kelas. Hal ini membantu kita dalam menafsirkan output model sebagai label kelas.

predicted_class_id = torch.argmax(probabilities, dim=-1).item(): Baris ini menggunakan argmax untuk mendapatkan indeks kelas yang memiliki probabilitas tertinggi, yang akan menjadi prediksi kelas dari model.

predicted_class_label = id2label[predicted_class_id]: Baris ini mengonversi indeks kelas yang diprediksi menjadi label kelas menggunakan pemetaan yang telah diperoleh dari id2label.

print("Predicted class:", predicted_class_label): Baris ini mencetak label kelas yang diprediksi oleh model.

print("Probabilities:", probabilities): Baris ini mencetak probabilitas untuk setiap kelas yang dihasilkan oleh model. Probabilitas ini menunjukkan seberapa yakin model terhadap setiap kelas yang diprediksikan.

In [6]:
tokenized_inputs = tokenizer(sequence, return_tensors="pt")
print(tokenized_inputs["input_ids"])

tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102]])


Baris ini menggunakan tokenizer yang telah diinisialisasi sebelumnya untuk memproses teks yang diberikan (sequence) dan menghasilkan representasi token dari teks tersebut dalam bentuk tensor PyTorch. Mari kita bahas lebih detail:

tokenizer(sequence, return_tensors="pt"): Ini adalah pemanggilan metode tokenizer yang menggunakan teks sequence sebagai input. Argumen return_tensors="pt" menunjukkan bahwa kita ingin mengembalikan representasi token dalam bentuk tensor PyTorch. Ini akan menghasilkan keluaran yang merupakan dictionary yang berisi representasi token dari teks input dalam bentuk tensor PyTorch.

tokenized_inputs["input_ids"]: Ini adalah akses ke entri "input_ids" dari dictionary tokenized_inputs, yang berisi tensor PyTorch yang merepresentasikan token-token dari teks input dalam bentuk ID-token. Ini adalah representasi utama dari teks input yang akan dimasukkan ke dalam model untuk analisis lebih lanjut.

In [7]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)

input_ids = torch.tensor([ids])
print("Input IDs:", input_ids)

output = model(input_ids)
print("Logits:", output.logits)

Input IDs: tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012]])
Logits: tensor([[-2.7276,  2.8789]], grad_fn=<AddmmBackward0>)


ode ini melakukan hal-hal berikut:

Menggunakan checkpoint yang telah ditentukan untuk memuat tokenizer dan model dari pustaka Transformers.

Mengekstraksi token dari teks input menggunakan tokenizer dan mengonversi token-token tersebut menjadi ID-token.

Menginisialisasi tensor PyTorch dari ID-token yang telah dihasilkan dan melakukan inferensi menggunakan model.

Mencetak tensor PyTorch input_ids yang merepresentasikan ID-token dari teks input.

Mencetak tensor logits yang dihasilkan oleh model, yang mewakili nilai-nilai mentah sebelum melewati fungsi aktivasi untuk memprediksi kelas dari teks input.

In [8]:
batched_ids = [
    [200, 200, 200],
    [200, 200]
]

In [9]:
padding_id = 100

batched_ids = [
    [200, 200, 200],
    [200, 200, padding_id],
]

In [10]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence1_ids = [[200, 200, 200]]
sequence2_ids = [[200, 200]]
batched_ids = [
    [200, 200, 200],
    [200, 200, tokenizer.pad_token_id],
]

print(model(torch.tensor(sequence1_ids)).logits)
print(model(torch.tensor(sequence2_ids)).logits)
print(model(torch.tensor(batched_ids)).logits)

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.


tensor([[ 1.5694, -1.3895]], grad_fn=<AddmmBackward0>)
tensor([[ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)
tensor([[ 1.5694, -1.3895],
        [ 1.3374, -1.2163]], grad_fn=<AddmmBackward0>)


In [11]:
batched_ids = [
    [200, 200, 200],
    [200, 200, tokenizer.pad_token_id],
]

attention_mask = [
    [1, 1, 1],
    [1, 1, 0],
]

outputs = model(torch.tensor(batched_ids), attention_mask=torch.tensor(attention_mask))
print(outputs.logits)

tensor([[ 1.5694, -1.3895],
        [ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)


In [13]:
max_sequence_length = 100  # Definisikan panjang maksimum yang diinginkan
sequence = sequence[:max_sequence_length]